name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up PHP
    - name: Set up PHP
      uses: shivammathur/setup-php@v3
      with:
        php-version: '8.1'

    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: composer install --no-dev --optimize-autoloader

    # Step 4: Remove .git and Deploy to Server
    - name: Deploy to Server
      env:
        DEPLOY_USER: BALAJI.A
        DEPLOY_HOST: 172.30.17.173
        DEPLOY_PATH: /var/www/html/quiz/
      run: |
        # Remove the .git directory
        rm -rf .git
        # Deploy files to the server
        rsync -avz ./ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
