name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up PHP
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'


    # Step 3: Install Dependencies



    # Step 4: Remove .git and Deploy to Server
    - name: Deploy to Server
      env:
        DEPLOY_USER: BALAJI.A
        DEPLOY_HOST: 172.30.17.173
        DEPLOY_PATH: /var/www/html

      run: |
        # Step 4.1: Verify if .git folder exists
        ls -la .git || echo ".git folder does not exist or already removed"

        # Step 4.2: Remove .git folder
        rm -rf .git
        
        # Step 4.3: Deploy code to the server
        rsync -avz ./ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
